# Generated by Django 4.2.3 on 2023-07-17 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_category_alter_food_name_food_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='food_type',
        ),
    ]
