# Generated by Django 4.2.3 on 2023-07-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_remove_food_food_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_suggested',
            field=models.BooleanField(default=False),
        ),
    ]
