# Generated by Django 4.0 on 2022-01-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_rename_foods_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_type',
            field=models.CharField(choices=[('br', 'Breakfast'), ('lu', 'Lunch'), ('di', 'Dinner'), ('dr', 'Drink')], default='dr', max_length=2),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
