# Generated by Django 4.0 on 2022-01-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_photo',
            field=models.ImageField(blank=True, null=True, upload_to='blogs'),
        ),
    ]
