# Generated by Django 4.0 on 2022-01-24 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_alter_blog_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tilte',
            new_name='title',
        ),
    ]
