# Generated by Django 4.0 on 2022-01-24 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_alter_comment_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commnet',
            new_name='comment',
        ),
    ]
