# Generated by Django 4.0 on 2022-01-29 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
