# Generated by Django 4.2.3 on 2023-07-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_remove_reservation_phone_alter_reservation_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='person',
            field=models.IntegerField(),
        ),
    ]
